apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-data-cronjob
spec:
  schedule: '* * * * *' # every minute
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
            - name: sync-data-job
              image: qu1etboy/k8s-jobs-demo:latest
              command: ['./sync-data-job']
              resources:
                requests:
                  cpu: '1000m'
                  memory: '2Gi'
                limits:
                  cpu: '2000m'
                  memory: '4Gi'
          restartPolicy: Never
